name: ez_localization
description: Setup a powerful localization system in your flutter application quickly and easily.
version: 1.0.0+2
homepage: https://github.com/Skyost/EzLocalization

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
