name: ez_localization
description: Setup a powerful localization system in your flutter application quickly and easily.
version: 1.1.0
homepage: https://github.com/Skyost/EzLocalization

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
