name: ez_localization
description: Setup a powerful localization system in your flutter application quickly and easily.
version: 1.1.1
homepage: https://github.com/Skyost/EzLocalization

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
